### ISSUE TITLE
Error running the az webapp deloy

### ISSUE THREAD

**Issue by bgawale** [Azure/gpt-rag-frontend#18]
After creating the deploy.zip, while running the zip deployment - the error is thrown with status code 401
_An error occured during deployment. Status Code: 401_

After running it with the --debug switch, it shows below insights
```
cli.azure.cli.command_modules.appservice.custom: Deployment API: https://webgpt0-[unique-name].scm.azurewebsites.net/api/publish?type=zip&async=true
urllib3.connectionpool: Starting new HTTPS connection (1): webgpt0-[unique-name].scm.azurewebsites.net:443
urllib3.connectionpool: https://webgpt0-[unique-name].scm.azurewebsites.net:443 "POST /api/publish?type=zip&async=true HTTP/1.1" 401 0
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 4655, in perform_onedeploy
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 4821, in _perform_onedeploy_internal
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/appservice/custom.py", line 4809, in _make_onedeploy_request
knack.util.CLIError: An error occured during deployment. Status Code: 401, Details:

cli.azure.cli.core.azclierror: An error occured during deployment. Status Code: 401, Details: 
az_command_data_logger: An error occured during deployment. Status Code: 401, Details:
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x047C70B8>]
```
Is there any particular setting that needs to be configured before running the deployment?

**Comment by bgawale** [comment]
Managed to resolve the error - had to enable the Basic Auth Publishing Configuration under the Platform Settings of Azure web app

![image](https://github.com/Azure/gpt-rag-frontend/assets/47916356/63c8007e-008a-450d-9d07-03c38c56f54c)
